# Generated by Django 5.2.3 on 2025-07-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_alter_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
